### ISSUE TITLE
GOD LEFT ME UNFINISHED

### ISSUE THREAD

**Issue by mypetbirdrules** [mypetbirdrules/tentacles#4]
OH GOD MY MIND

**Comment by VlentfulGaming** [comment]
What is wrong? For real. The #video class isn't needed. But you better not take away the .video class or else you are going to have broken CSS. And items can have the same class. Maybe not ID because of JavaScript. But, make sure you keep those classes. Look at YouTube, they have multiple instances of a class everywhere.

**Comment by KyleStank** [comment]
Close me. I will be finished.
